export const ProductData = [
  {
    id: '1',
    title: 'activia',
    description: 'activia',
    img: '/cart/activiafin.png',
    type: 'one',
    price: 12,
  },
  {
    id: '2',
    title: 'blueberry',
    description: 'blueberry',
    img: '/cart/blueberry.png',
    type: 'multiply',
    price: 13,
  },
  {
    id: '3',
    title: 'buttermilk',
    description: 'buttermilk',
    img: '/cart/buttermilk.png',
    type: 'oneTime',
    price: 8,
  },
  {
    id: '4',
    title: 'L&F',
    description: 'L&F',
    img: '/cart/L&F.png',
    type: 'oneTime',
    price: 11,
  },
  {
    id: '5',
    title: 'MMMH',
    description: 'MMMH',
    img: '/cart/MMMH.png',
    type: 'multiply',
    price: 10,
  },
  {
    id: '6',
    title: 'vanilla fruit',
    description: 'vanilla fruit',
    img: '/cart/vanilla_fruit.png',
    type: 'one',
    price: 5,
  },
]
